### ISSUE TITLE
Running the Simulation for the first time generates error

### ISSUE THREAD

**Issue by meirshad** [saburhb/FlyNetSim#9]
Hello,
I want to run the FlyNetSim and as i try to run the simulation for the first time i get this error as bellow.

Traceback (most recent call last):
  File "FlyNetSim.py", line 84, in <module>
    tree.write(xml_path + "/config.xml")
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 802, in write
    file = open(file_or_filename, "wb")
IOError: [Errno 2] No such file or directory: '/home/FlyNetSim/NetSim/ns-allinone-3.27/ns-3.27/config.xml'

Regards
Irshad Ullah

**Comment by jpsgill** [comment]
Hi,
I have the same issue. Running on Ubuntu 18.04 LTS. Any help would be appreciated. 
After running python FlyNetSim command, I get this error.

Traceback (most recent call last):
  File "FlyNetSim.py", line 84, in <module>
    tree.write(xml_path + "/config.xml")
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 802, in write
    file = open(file_or_filename, "wb")
IOError: [Errno 2] No such file or directory: '/home/FlyNetSim/NetSim/ns-allinone-3.27/ns-3.27/config.xml'

Thank you for your time. 

Best,
Gill

**Comment by jpsgill** [comment]
**Give Absolute Path**
Open FlyNetSim.py using gedit and change the 
->tree.write(xml_path + "/config.xml")  TO
->tree.write(xml_path + "Give absolute path here")

Hope this helps.

Best
Gill

**Comment by meirshad** [comment]
> **Give Absolute Path**
> Open FlyNetSim.py using gedit and change the
> ->tree.write(xml_path + "/config.xml") TO
> ->tree.write(xml_path + "Give absolute path here")
> 
> Hope this helps.
> 
> Best
> Gill

Thank you so much for the reply, even after providing the absolute path , i still get the error as bellow

File "FlyNetSim.py", line 85, in <module>
    tree.write(xml_path + "/home/irshad/FlyNetSim/NetSim/ns-allinone-3.27/ns-3.27/config.xml")
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 802, in write
    file = open(file_or_filename, "wb")
IOError: [Errno 2] No such file or directory: '/home/FlyNetSim/NetSim/ns-allinone-3.27/ns-3.27/home/irshad/FlyNetSim/NetSim/ns-allinone-3.27/ns-3.27/config.xml'

**Comment by pj220iw** [comment]
Having same issue. Any fix ?

**Comment by meirshad** [comment]
Thanks for the reply,
I still got the same issue, is it possible if you can send me the screen shot in order to fix it, as i provided the absolute path but get the same error.
Thanks once again for sparing time.

**Comment by Wanjoo** [comment]
> Thanks for the reply,
> I still got the same issue, is it possible if you can send me the screen shot in order to fix it, as i provided the absolute path but get the same error.
> Thanks once again for sparing time.

delete xml_path and Input your absolute path 
like tree.write("/home/irshad/FlyNetSim/NetSim/ns-allinone-3.27/ns-3.27/config.xml")
